<a href="https://colab.research.google.com/github/ziwon-hwang/DALC_Scalar/blob/main/DALC_scalar4_%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%8D%B0%EC%9D%B4%ED%84%B0_%ED%83%80%EC%9E%85%EA%B3%BC_numpy%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 기초

## 넘파이 패키지 불러오기

In [1]:
# 넘파이 패키지를 불러오기 np로 줄여쓰기# 넘파이 패키지를 불러오기 np로 줄여쓰기
import numpy as np

## array 정의 및 생성

In [22]:
# 넘파이 array를 사용하여 a라는 변수에 1부터 10까지의 숫자 리스트 배열을 생성하기
a=np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
#파이썬의 기본 range 함수와 비슷한 넘파이 range 함수를 사용하여 ndarray를 만들 수 있습니다:
a1=np.arange(0,10,2)
a1

array([0, 2, 4, 6, 8])

## 배열 구성

In [9]:
# full 함수를 사용하여 b라는 변수에 2.71 수로 3 X 4 다차원 배열 만들기
a3=np.full((3,4),2.71)
a3

array([[2.71, 2.71, 2.71, 2.71],
       [2.71, 2.71, 2.71, 2.71],
       [2.71, 2.71, 2.71, 2.71]])

In [14]:
# arrange 함수를 사용하여 c라는 변수에 0부터 10까지 짝수만 있는 배열 구성하기
c=np.arange(0,10,2)
c

array([0, 2, 4, 6, 8])

In [18]:
# linspace 함수를 사용하여 d라는 변수에 0부터 1까지 4개 요소 값을 가진 배열 생성하기
a4=np.linspace(0,10,4)
a4

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [20]:
# randint 함수를 사용하여 0 부터 100까지 수를 2 X 2 배열로 생성하기
a5=np.random.randint(1,100,(2,2))
a5

array([[86, 78],
       [84, 93]])

## 배열 인덱싱

In [23]:
# a변수에서 인덱스 2 (앞에서 3번째) 와 인덱스 -3 (뒤에서 3번째)에 해당하는 수 가져오기
a[2],a[-3]

(3, 8)

In [26]:
# a 변수에서 인덱스 3부터 9 까지 슬라이싱하기
a[3:10]

array([ 4,  5,  6,  7,  8,  9, 10])

## 배열 재구조화

In [27]:
#차원의 개수 알아보는 함수
a.ndim

1

In [28]:
#차원의 크기 알아보는 함수
a.shape

(10,)

In [30]:
#전체 배열크기 알아보는 함수
a.size

10

In [41]:
#0부터10까지 정수를 가진 x변수에서 4~7까지의 요소를 가진 하위배열생성
x=np.arange(0,11)
print(x)
print(x[4:8])

[ 0  1  2  3  4  5  6  7  8  9 10]
[4 5 6 7]


In [43]:
#0부터10까지 정수를 가진 x변수에서 첫번째 다섯 요소를 가진 하위 배열 생성
x[:6]

array([0, 1, 2, 3, 4, 5])

In [45]:
#0부터10까지 정수를 가진 x변수에서 인덱스 5 이후의 요소를 가진 하위 배열을 생성
x[6:]

array([ 6,  7,  8,  9, 10])

In [49]:
# 인덱스 0,1행과 인덱스 0,1,2열 즉 2행3열인 다차원 하위 배열 생성(콤마이용하기)
z=np.array([[2,4,6,8],[3,6,9,12],[4,8,12,16]])
z[:2,:3]

array([[2, 4, 6],
       [3, 6, 9]])

In [ ]:
#1부터 10까지 배열을 3행3열로 재배열하기(reshape사용)

## 배열 결합

In [50]:
#두개의 배열 결합하기
x=np.array([1,2,3])
y=np.array([3,2,1])
z=np.concatenate([x,y])
z

array([1, 2, 3, 3, 2, 1])

In [52]:
#수직으로 두개의 배열 결합하기
z1=np.vstack([x,y])
z1

array([[1, 2, 3],
       [3, 2, 1]])

In [54]:
#수평으로 두개의 배열 결합하기
z2=np.hstack([x,y])
z2

array([1, 2, 3, 3, 2, 1])

## 배열 분할

In [56]:
#7개의 숫자를 가진 리스트 x를 3개의 변수 x1,x2,x3로 분할하기
x=[1,2,3,4,5,6,7]
x1,x2,x3=np.split(x,[3,5])#자르는 지점 인덱스 3과 인덱스 5
print(x1,x2,x3)

[1 2 3] [4 5] [6 7]


In [61]:
#4행4열 차원을 배열이 상하 2개로 나누게 분할
grid=np.arange(16).reshape((4,4))
upper,lower=np.vsplit(grid,[2])
print(grid)
print('--------')
print(upper)
print("--------")
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
--------
[[0 1 2 3]
 [4 5 6 7]]
--------
[[ 8  9 10 11]
 [12 13 14 15]]


# Numpy 심화

## 유니버셜함수

In [62]:
# zeros 함수는 0으로 채워진 배열을 만듭니다:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [63]:
#2D 배열(즉, 행렬)을 만들려면 원하는 행과 열의 크기를 튜플로 전달합니다. 예를 들어 다음은 3 \times 4 크기의 행렬입니다:

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
a.shape

(3, 4)

In [66]:
a.ndim # len(a.shape)와 같습니다

2

In [67]:
a.size

12

In [68]:
# 초기화되지 않은 2 \times 3 크기의 배열을 만듭니다(배열의 내용은 예측이 불가능하며 메모리 상황에 따라 달라집니다):

np.empty((2,3))

array([[4.6539794e-310, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [69]:
#array 함수는 파이썬 리스트를 사용하여 ndarray를 초기화합니다:

np.array([[1,2,3,4], [10, 20, 30, 40]])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [71]:
 x = np.array([-10, -5, 0, 3, 7])
# x에 있는 배열을 모두 양의 정수로 반환하기
np.abs(x)

array([10,  5,  0,  3,  7])

In [73]:
# 모두 양의 정수가 된 배열 x를 자연로그 배열로 반환하기
print(np.log(x))

[       nan        nan       -inf 1.09861229 1.94591015]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  


## 집계함수

In [74]:
x=np.array([-2,-1,0,1,2])
"절댓값을 씌우려면?"
힌트: "np.absolute(x)"
np.abs(x)

array([2, 1, 0, 1, 2])

In [76]:
#삼각함수
theta = np.linspace(0,np.pi,3)
print("theta=" , theta)
print(" 코사인 함수 =",np.cos(theta))
print("탐젠트 함수= ", np.tan(theta)) 



theta= [0.         1.57079633 3.14159265]
 코사인 함수 = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
탐젠트 함수=  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [77]:
#역삼각함수
print("역 사인함수=",np.arcsin(theta))
print("역 코사인함수=",np.arccos(theta))
print("역 탄젠트함수=",np.arctan(theta))

역 사인함수= [ 0. nan nan]
역 코사인함수= [1.57079633        nan        nan]
역 탄젠트함수= [0.         1.00388482 1.26262726]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in arcsin
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in arccos
  This is separate from the ipykernel package so we can avoid doing imports until


In [79]:
#로그함수
x=[1,2,4,10]
print("자연로그=",np.log(x))
print("밑이2인 로그함수=",np.log2(x))
print("밑이 10인 로그함수=",np.log10(x))

자연로그= [0.         0.69314718 1.38629436 2.30258509]
밑이2인 로그함수= [0.         1.         2.         3.32192809]
밑이 10인 로그함수= [0.         0.30103    0.60205999 1.        ]


In [82]:
#지수함수
x=[1,2,3]
print("e^x=",np.exp(x))
print("2^x",np.power(2,x))
print("3^x=",np.power(3,x))

e^x= [ 2.71828183  7.3890561  20.08553692]
2^x [2 4 8]
3^x= [ 3  9 27]


In [83]:
#out 인자 
x=np.arange(5)
y=np.empty(5)
np.multiply(x,10,out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [84]:
#out 인자를 활용하여 배열 슬라이싱
x=np.arange(5)
y=np.empty(10)
np.power(2,x,out=y[::2])
print(y)

[1.00000000e+000 6.79038653e-313 2.00000000e+000 6.79038653e-313
 4.00000000e+000 6.79038653e-313 8.00000000e+000 2.14321575e-312
 1.60000000e+001 0.00000000e+000]


In [85]:
#reduce 함수
x=np.arange(1,5)
np.add.reduce(x)#1부터4까지 더하기

10

In [86]:
#sum,max,min함수
s=np.random.random(1000)
print("s의최솟값=",np.min(s))
print("s의최댓값=",np.max(s))


s의최솟값= 0.001161803296939934
s의최댓값= 0.9987470803730623


In [88]:
#axis 인자
m=np.random.random((3,4))
"axis=0: 열기준 집계연산"
print(m.max(axis=0))

"axis=1: 행기준 집계연산"
print(m.max(axis=1))
"axis=none: 배열 내 모든 요소의 집계연산axis 인자"
print(m.max(axis=1))

[0.76506198 0.4818931  0.37649789 0.89852821]
[0.6830184  0.77249146 0.89852821]
[0.6830184  0.77249146 0.89852821]


In [ ]:
m= np.random.random((3,4))
print(m)

## 브로드캐스팅 연산

In [90]:
# 크기가 같은 어레이의 연산을 하기
x=np.array([0,1,2])
y=np.array([3,3,3])
x+y

array([3, 4, 5])

In [92]:
# 배열의 크기를 늘려서 연산하기
x=np.array([0,1,2])
x+10

array([10, 11, 12])

## 비교연산자

In [93]:
# any 함수를 이용하여 하나라도 만족하면 true를 산출하는 코드만들기
x=np.arange(10)
np.any(x<5),np.any(x<0)

(True, False)

In [95]:
# all함수를 이용하여 true산출 코드 만들기
x=np.arange(10)
np.all(x>5),np.all(x<10)

(False, True)

In [108]:
# 1~5사이의 구간에서 5개 정수를 무작위로 발생시켜 1차원배열 2개변수를 생성하고 이에대한 불리언 값 결과내기
a=np.random.randint(1,5,5)
b=np.random.randint(1,5,5)
print("a의값=",a,"b의 값=",b,a==b)

a의값= [2 1 3 1 2] b의 값= [3 4 4 1 1] [False False False  True False]


## 팬시 인덱싱

In [112]:
#배열을 생성하여 인덱싱하기
a=np.arange(10)
b=np.array([3,6,9])
a[b]

array([3, 6, 9])

In [117]:
#인덱스 값을 가진 2차원 배열(예를 들어 row=np.array([0,1,2]))을 이용하여 인덱싱
row=np.array([0,1,2])
col=np.array([2,1,3])
print(x,"--->",x[row,col])

[[2 3 7 3]
 [9 3 8 5]
 [3 9 8 8]] ---> [7 3 8]


## 정렬 

In [118]:
#np.sort함수를 이용하여 복사하기
x=np.array([4,1,5,2,3])
print(x,np.sort(x))

[4 1 5 2 3] [1 2 3 4 5]


In [119]:
#변수.sort함수를 이용하여 정렬하기
x=np.array([4,1,5,2,3])
x.sort()
print(x)

[1 2 3 4 5]


In [123]:
#np.arsort함수 이용하여 정렬 요소의 인덱스를 반환하기
x=np.array([4,1,5,2,3])
i = np.argsort(x)
print(i)

[1 3 4 0 2]


In [125]:
#x_reverse를 이용하여 내림차순
x=np.array([4,1,5,2,3])
x_reverse=np.sort(x)[::-1]
print(x_reverse)

[5 4 3 2 1]


In [127]:
#axis를 이용하여 각 열을 기준으로 정렬하기
x=np.array([[2,0,6],[7,3,4],[2,5,3]])
np.sort(x,axis=0)

array([[2, 0, 3],
       [2, 3, 4],
       [7, 5, 6]])

In [128]:
#axis를 이용하여 각 행을 기준으로 정렬하기#axis를 이용하여 각 행을 기준으로 정렬하기
np.sort(x,axis=1)

array([[0, 2, 6],
       [3, 4, 7],
       [2, 3, 5]])